export const siteUrl = 'https://metadataremovertool.com';

export const languages = {
  en: { label: 'English', hreflang: 'en', ogLocale: 'en_US' },
  es: { label: 'Español', hreflang: 'es', ogLocale: 'es_ES' },
  ja: { label: '日本語', hreflang: 'ja', ogLocale: 'ja_JP' },
  fr: { label: 'Français', hreflang: 'fr', ogLocale: 'fr_FR' },
  de: { label: 'Deutsch', hreflang: 'de', ogLocale: 'de_DE' },
  pt: { label: 'Português', hreflang: 'pt-BR', ogLocale: 'pt_BR' },
  ko: { label: '한국어', hreflang: 'ko', ogLocale: 'ko_KR' },
  it: { label: 'Italiano', hreflang: 'it', ogLocale: 'it_IT' },
  id: { label: 'Bahasa Indonesia', hreflang: 'id', ogLocale: 'id_ID' },
} as const;

export type Lang = keyof typeof languages;
export const translatedLangs = Object.keys(languages).filter((lang) => lang !== 'en') as Exclude<Lang, 'en'>[];

export function languagePath(lang: Lang) {
  return lang === 'en' ? '/' : `/${lang}/`;
}

export const alternates = [
  ...Object.entries(languages).map(([lang, data]) => ({ lang: data.hreflang, href: `${siteUrl}${languagePath(lang as Lang)}` })),
  { lang: 'x-default', href: `${siteUrl}/` },
];

type LocalizedHome = {
  title: string;
  description: string;
  h1: string;
  lead: string;
  privateLabel: string;
  benefits: string[];
  uploadTitle: string;
  uploadText: string;
  choose: string;
  localTitle: string;
  localText: string;
  howKicker: string;
  howTitle: string;
  steps: Array<{ title: string; text: string }>;
  aboutKicker: string;
  aboutTitle: string;
  about: string[];
  guideTitle: string;
  guide: Array<{ title: string; text: string }>;
  faqTitle: string;
  faqIntro: string;
  faqs: Array<{ question: string; answer: string }>;
  footer: string;
};

export const homeContent: Record<Exclude<Lang, 'en'>, LocalizedHome> = {
  es: {
    title: 'Eliminar metadatos de fotos, imágenes y PDF gratis',
    description: 'Elimina metadatos EXIF, GPS, cámara, autor y fechas de fotos, imágenes y PDF. Herramienta gratis, privada y sin subir archivos.',
    h1: 'Eliminador de metadatos gratis para fotos, imágenes y PDF',
    lead: 'Revisa y elimina datos ocultos como GPS, EXIF, cámara, autor, dispositivo y fechas antes de compartir. Todo funciona localmente en tu navegador.',
    privateLabel: 'Privacidad desde el diseño',
    benefits: ['Sin subir archivos', 'Sin crear una cuenta', 'Verificación después de limpiar'],
    uploadTitle: 'Suelta archivos para iniciar el análisis', uploadText: 'Elige uno o varios archivos. También puedes pegar una imagen desde el portapapeles.', choose: 'Elegir archivos',
    localTitle: 'Tus archivos permanecen en tu dispositivo.', localText: 'El análisis, la limpieza y la verificación se ejecutan en este navegador. No almacenamos ni recibimos tus archivos.',
    howKicker: 'Comprueba antes de borrar', howTitle: 'Entiende lo que revela el archivo y limpia solo lo necesario.',
    steps: [{ title: 'Detectar', text: 'Busca campos EXIF, GPS, IPTC, XMP, cámara y documento compatibles.' }, { title: 'Explicar', text: 'Convierte etiquetas técnicas en información clara sobre privacidad.' }, { title: 'Elegir', text: 'Usa una limpieza privada, completa, para fotógrafos o personalizada.' }, { title: 'Verificar', text: 'Analiza de nuevo la copia limpia y muestra qué información queda.' }],
    aboutKicker: 'Metadatos y privacidad', aboutTitle: '¿Qué hace un eliminador de metadatos?',
    about: ['Los metadatos son información guardada junto al contenido visible. Una foto puede incluir coordenadas GPS, fecha, modelo de cámara, objetivo, número de serie, autor o historial de edición. Un PDF puede revelar título, autor, creador, productor, palabras clave y fechas.', 'Esta herramienta muestra los campos detectados antes de modificar el archivo. Así puedes decidir entre eliminar información sensible, quitar todos los datos compatibles o conservar ajustes fotográficos seguros cuando el formato lo permite.', 'El procesamiento ocurre dentro del navegador. La copia original no se modifica y el archivo no se envía a un servidor. Tras la limpieza, la copia se vuelve a analizar para que puedas comprobar el resultado antes de compartirla.'],
    guideTitle: 'Cómo eliminar metadatos de una foto o un PDF', guide: [{ title: 'Añade el archivo', text: 'Selecciona JPG, PNG, WebP o PDF y espera al análisis local.' }, { title: 'Revisa y elige', text: 'Comprueba ubicación, identidad, dispositivo, fechas y datos técnicos, y selecciona el modo de limpieza.' }, { title: 'Descarga la copia verificada', text: 'La herramienta vuelve a escanear el resultado y conserva intacto el original.' }],
    faqTitle: 'Preguntas sobre eliminar metadatos', faqIntro: 'Respuestas directas sobre EXIF, GPS, imágenes y documentos PDF.',
    faqs: [{ question: '¿Cómo quitar los metadatos de una foto?', answer: 'Elige una foto JPG, PNG o WebP, revisa los campos encontrados, selecciona una limpieza y descarga la copia verificada.' }, { question: '¿Se suben mis imágenes?', answer: 'No. Los archivos se leen y se limpian localmente en tu navegador.' }, { question: '¿Puede eliminar la ubicación GPS?', answer: 'Sí, cuando las coordenadas GPS están en metadatos compatibles, aparecen en el informe y se eliminan con los modos adecuados.' }, { question: '¿Funciona con PDF?', answer: 'Sí. Detecta y permite quitar campos habituales como autor, título, creador, productor, asunto, palabras clave y fechas.' }, { question: '¿Pierdo el archivo original?', answer: 'No. Se crea una nueva copia; el original nunca se sobrescribe.' }], footer: 'Limpieza privada de archivos en tu navegador.',
  },
  ja: {
    title: '写真・画像・PDFのメタデータを無料で削除', description: '写真、画像、PDFからEXIF、GPS、カメラ、作成者、日時などのメタデータを無料で削除。アップロード不要でブラウザ内処理。',
    h1: '写真・画像・PDFの無料メタデータ削除ツール', lead: '共有前にGPS、EXIF、カメラ、作成者、端末、日時などの隠れた情報を確認して削除できます。処理はすべてブラウザ内で行われます。', privateLabel: 'プライバシー重視', benefits: ['サーバーへ送信しない', 'アカウント不要', '削除後に再確認'],
    uploadTitle: 'ファイルをドロップしてスキャンを開始', uploadText: '1つまたは複数のファイルを選択できます。クリップボードから画像を貼り付けることもできます。', choose: 'ファイルを選択', localTitle: 'ファイルは端末内に残ります。', localText: '解析、削除、確認はこのブラウザ内で実行されます。ファイルのアップロードや保存は行いません。',
    howKicker: '削除前に内容を確認', howTitle: 'ファイルが何を明らかにするかを確認し、必要な情報だけを削除。', steps: [{ title: '検出', text: '対応するEXIF、GPS、IPTC、XMP、カメラ、PDF情報を探します。' }, { title: '説明', text: '技術的な項目を分かりやすいプライバシー情報として表示します。' }, { title: '選択', text: 'プライバシー、完全削除、写真家向け、カスタムから選べます。' }, { title: '検証', text: '処理後のファイルを再解析し、残った情報を表示します。' }],
    aboutKicker: 'メタデータとプライバシー', aboutTitle: 'メタデータ削除ツールとは？', about: ['メタデータは、見える画像や文書とは別に保存される情報です。写真にはGPS座標、撮影日時、カメラやレンズ、シリアル番号、作成者、編集履歴が含まれることがあります。PDFにはタイトル、作成者、作成ソフト、キーワード、日時などが残る場合があります。', 'このツールは変更前に検出した項目を表示します。機密情報だけを削除するか、対応するメタデータをすべて削除するか、対応形式で安全な撮影設定を残すかを選べます。', '処理はブラウザ内で完結し、元のファイルは変更されません。作成されたコピーを再スキャンするため、共有前に削除結果を確認できます。'],
    guideTitle: '写真やPDFのメタデータを削除する方法', guide: [{ title: 'ファイルを追加', text: 'JPG、PNG、WebP、PDFを選び、ローカル解析を待ちます。' }, { title: '確認して選択', text: '位置、個人情報、端末、日時、技術情報を確認し、削除方法を選びます。' }, { title: '確認済みコピーを保存', text: '出力を再スキャンしてからダウンロードできます。元ファイルはそのままです。' }],
    faqTitle: 'メタデータ削除のよくある質問', faqIntro: 'EXIF、GPS、画像、PDFについて簡潔に回答します。', faqs: [{ question: '写真のメタデータを削除するには？', answer: 'JPG、PNG、WebPを選び、検出項目を確認して削除モードを選び、確認済みコピーを保存します。' }, { question: '画像はアップロードされますか？', answer: 'いいえ。読み取りと処理はブラウザ内で行われます。' }, { question: 'GPS位置情報を削除できますか？', answer: '対応するGPSタグがある場合はレポートに表示され、適切なモードで削除できます。' }, { question: 'PDFにも対応していますか？', answer: 'はい。作成者、タイトル、作成ソフト、件名、キーワード、日時などに対応します。' }, { question: '元ファイルは消えますか？', answer: 'いいえ。新しいコピーを作成し、元ファイルは上書きしません。' }], footer: 'ブラウザ内で行うプライベートなファイル整理。',
  },
  fr: {
    title: 'Supprimer les métadonnées des photos, images et PDF', description: 'Supprimez gratuitement EXIF, GPS, appareil, auteur et dates des photos, images et PDF, sans téléverser vos fichiers.',
    h1: 'Suppresseur de métadonnées gratuit pour photos, images et PDF', lead: 'Inspectez et supprimez les données cachées — GPS, EXIF, appareil, auteur et dates — avant le partage. Tout reste dans votre navigateur.', privateLabel: 'Confidentiel par conception', benefits: ['Aucun téléversement', 'Aucun compte', 'Vérification après nettoyage'],
    uploadTitle: 'Déposez des fichiers pour lancer l’analyse', uploadText: 'Choisissez un ou plusieurs fichiers, ou collez une image depuis le presse-papiers.', choose: 'Choisir des fichiers', localTitle: 'Vos fichiers restent sur votre appareil.', localText: 'L’analyse, le nettoyage et la vérification s’exécutent dans ce navigateur. Aucun fichier n’est envoyé ni stocké.',
    howKicker: 'Vérifier avant de supprimer', howTitle: 'Voyez ce que le fichier révèle et ne retirez que ce qui est nécessaire.', steps: [{ title: 'Détecter', text: 'Recherche les champs EXIF, GPS, IPTC, XMP, appareil et PDF compatibles.' }, { title: 'Expliquer', text: 'Traduit les champs techniques en informations de confidentialité claires.' }, { title: 'Choisir', text: 'Sélectionnez un nettoyage privé, complet, photographe ou personnalisé.' }, { title: 'Vérifier', text: 'Analyse à nouveau la copie et indique les informations restantes.' }],
    aboutKicker: 'Métadonnées et vie privée', aboutTitle: 'À quoi sert un suppresseur de métadonnées ?', about: ['Les métadonnées accompagnent le contenu visible. Une photo peut contenir les coordonnées GPS, la date, l’appareil, l’objectif, un numéro de série, l’auteur ou l’historique d’édition. Un PDF peut révéler son titre, son auteur, le logiciel créateur, le producteur, les mots-clés et les dates.', 'Cet outil affiche les champs détectés avant toute modification. Vous pouvez retirer les informations sensibles, supprimer toutes les données prises en charge ou conserver certains réglages photographiques lorsque le format le permet.', 'Le traitement reste dans le navigateur et le fichier original n’est jamais remplacé. La copie nettoyée est analysée une seconde fois afin de vérifier le résultat avant son partage.'],
    guideTitle: 'Comment supprimer les métadonnées d’une photo ou d’un PDF', guide: [{ title: 'Ajoutez le fichier', text: 'Sélectionnez un JPG, PNG, WebP ou PDF et attendez l’analyse locale.' }, { title: 'Contrôlez et choisissez', text: 'Examinez localisation, identité, appareil, dates et détails techniques, puis choisissez le nettoyage.' }, { title: 'Téléchargez la copie vérifiée', text: 'Le résultat est rescanné et l’original reste intact.' }],
    faqTitle: 'Questions sur la suppression des métadonnées', faqIntro: 'Réponses directes sur EXIF, GPS, images et PDF.', faqs: [{ question: 'Comment effacer les métadonnées d’une photo ?', answer: 'Choisissez un JPG, PNG ou WebP, examinez les champs, sélectionnez un nettoyage puis téléchargez la copie vérifiée.' }, { question: 'Mes images sont-elles téléversées ?', answer: 'Non. Les fichiers sont lus et nettoyés localement dans votre navigateur.' }, { question: 'Peut-on supprimer la position GPS ?', answer: 'Oui, les coordonnées compatibles sont affichées et retirées par les modes appropriés.' }, { question: 'L’outil fonctionne-t-il avec les PDF ?', answer: 'Oui, pour les champs courants comme auteur, titre, créateur, producteur, sujet, mots-clés et dates.' }, { question: 'Le fichier original est-il modifié ?', answer: 'Non. Une nouvelle copie est créée sans écraser l’original.' }], footer: 'Nettoyage privé des fichiers dans votre navigateur.',
  },
  de: {
    title: 'Metadaten aus Fotos, Bildern und PDFs kostenlos entfernen', description: 'EXIF-, GPS-, Kamera-, Autor- und Datumsangaben kostenlos aus Fotos, Bildern und PDFs entfernen – privat im Browser.',
    h1: 'Kostenloser Metadaten-Entferner für Fotos, Bilder und PDFs', lead: 'Prüfe und entferne versteckte GPS-, EXIF-, Kamera-, Autor-, Geräte- und Datumsangaben vor dem Teilen. Alles läuft lokal im Browser.', privateLabel: 'Datenschutz von Anfang an', benefits: ['Keine Datei-Uploads', 'Kein Konto nötig', 'Prüfung nach der Bereinigung'],
    uploadTitle: 'Dateien ablegen und Datenschutzprüfung starten', uploadText: 'Wähle eine oder mehrere Dateien oder füge ein Bild aus der Zwischenablage ein.', choose: 'Dateien auswählen', localTitle: 'Deine Dateien bleiben auf deinem Gerät.', localText: 'Analyse, Bereinigung und Prüfung laufen in diesem Browser. Dateien werden weder hochgeladen noch gespeichert.',
    howKicker: 'Erst prüfen, dann entfernen', howTitle: 'Erkenne, was eine Datei verrät, und entferne nur die nötigen Angaben.', steps: [{ title: 'Erkennen', text: 'Findet unterstützte EXIF-, GPS-, IPTC-, XMP-, Kamera- und PDF-Felder.' }, { title: 'Erklären', text: 'Übersetzt technische Felder in verständliche Datenschutzinformationen.' }, { title: 'Auswählen', text: 'Wähle Datenschutz-, Komplett-, Fotografen- oder benutzerdefinierte Bereinigung.' }, { title: 'Überprüfen', text: 'Scannt die bereinigte Kopie erneut und zeigt verbleibende Angaben.' }],
    aboutKicker: 'Metadaten und Privatsphäre', aboutTitle: 'Was macht ein Metadaten-Entferner?', about: ['Metadaten werden zusätzlich zum sichtbaren Inhalt gespeichert. Fotos können GPS-Koordinaten, Aufnahmezeit, Kamera, Objektiv, Seriennummer, Urheber oder Bearbeitungsverlauf enthalten. PDFs können Titel, Autor, Erstellungsprogramm, Produzent, Stichwörter und Datumsangaben preisgeben.', 'Das Werkzeug zeigt erkannte Felder vor jeder Änderung. Du kannst sensible Daten entfernen, alle unterstützten Metadaten löschen oder bei geeigneten Formaten sichere Kameraeinstellungen behalten.', 'Die Verarbeitung findet im Browser statt. Das Original wird nicht überschrieben und keine Datei an einen Server gesendet. Die bereinigte Kopie wird erneut analysiert, damit du das Ergebnis vor dem Teilen prüfen kannst.'],
    guideTitle: 'Metadaten aus Foto oder PDF entfernen', guide: [{ title: 'Datei hinzufügen', text: 'JPG, PNG, WebP oder PDF auswählen und die lokale Analyse abwarten.' }, { title: 'Prüfen und wählen', text: 'Standort, Identität, Gerät, Daten und technische Angaben prüfen und einen Modus wählen.' }, { title: 'Geprüfte Kopie laden', text: 'Das Ergebnis wird erneut gescannt; das Original bleibt unverändert.' }],
    faqTitle: 'Häufige Fragen zu Metadaten', faqIntro: 'Klare Antworten zu EXIF, GPS, Bildern und PDF-Dokumenten.', faqs: [{ question: 'Wie entferne ich Metadaten aus einem Foto?', answer: 'JPG, PNG oder WebP wählen, gefundene Felder prüfen, Bereinigung auswählen und die geprüfte Kopie laden.' }, { question: 'Werden meine Bilder hochgeladen?', answer: 'Nein. Lesen und Bereinigen erfolgen lokal im Browser.' }, { question: 'Kann GPS entfernt werden?', answer: 'Ja. Unterstützte GPS-Daten erscheinen im Bericht und werden mit den passenden Modi entfernt.' }, { question: 'Funktioniert das mit PDFs?', answer: 'Ja, unter anderem für Autor, Titel, Ersteller, Produzent, Betreff, Stichwörter und Datumsfelder.' }, { question: 'Wird das Original verändert?', answer: 'Nein. Es wird eine neue Kopie erstellt.' }], footer: 'Private Dateibereinigung direkt im Browser.',
  },
  pt: {
    title: 'Removedor de metadados de fotos, imagens e PDF grátis', description: 'Remova EXIF, GPS, câmera, autor e datas de fotos, imagens e PDF grátis, sem enviar seus arquivos.',
    h1: 'Removedor de metadados grátis para fotos, imagens e PDFs', lead: 'Veja e remova dados ocultos como GPS, EXIF, câmera, autor, aparelho e datas antes de compartilhar. Tudo acontece localmente no navegador.', privateLabel: 'Privacidade desde o início', benefits: ['Sem upload de arquivos', 'Sem criar conta', 'Verificação após a limpeza'],
    uploadTitle: 'Solte arquivos para iniciar a análise', uploadText: 'Escolha um ou vários arquivos. Você também pode colar uma imagem da área de transferência.', choose: 'Escolher arquivos', localTitle: 'Seus arquivos ficam no seu dispositivo.', localText: 'A análise, a limpeza e a verificação rodam neste navegador. Nenhum arquivo é enviado ou armazenado.',
    howKicker: 'Confira antes de apagar', howTitle: 'Entenda o que o arquivo revela e remova apenas o necessário.', steps: [{ title: 'Detectar', text: 'Encontra campos compatíveis de EXIF, GPS, IPTC, XMP, câmera e PDF.' }, { title: 'Explicar', text: 'Transforma campos técnicos em informações claras de privacidade.' }, { title: 'Escolher', text: 'Use limpeza de privacidade, completa, para fotógrafos ou personalizada.' }, { title: 'Verificar', text: 'Analisa novamente a cópia e mostra quais informações permaneceram.' }],
    aboutKicker: 'Metadados e privacidade', aboutTitle: 'O que faz um removedor de metadados?', about: ['Metadados são informações guardadas junto do conteúdo visível. Uma foto pode conter coordenadas GPS, data, modelo da câmera, lente, número de série, autor ou histórico de edição. Um PDF pode revelar título, autor, aplicativo criador, produtor, palavras-chave e datas.', 'A ferramenta mostra os campos encontrados antes de alterar o arquivo. Você pode remover informações sensíveis, apagar todos os metadados compatíveis ou manter configurações fotográficas seguras quando o formato permitir.', 'O processamento ocorre no navegador, sem substituir o original e sem enviar o arquivo a um servidor. Depois da limpeza, a cópia é analisada novamente para confirmar o resultado antes do compartilhamento.'],
    guideTitle: 'Como remover metadados de foto ou PDF', guide: [{ title: 'Adicione o arquivo', text: 'Selecione JPG, PNG, WebP ou PDF e aguarde a análise local.' }, { title: 'Confira e escolha', text: 'Revise localização, identidade, aparelho, datas e dados técnicos e selecione a limpeza.' }, { title: 'Baixe a cópia verificada', text: 'O resultado é escaneado novamente e o original continua intacto.' }],
    faqTitle: 'Perguntas sobre remover metadados', faqIntro: 'Respostas diretas sobre EXIF, GPS, imagens e PDF.', faqs: [{ question: 'Como tirar metadados de uma foto?', answer: 'Escolha JPG, PNG ou WebP, confira os campos, selecione a limpeza e baixe a cópia verificada.' }, { question: 'Minhas imagens são enviadas?', answer: 'Não. Os arquivos são lidos e limpos localmente no navegador.' }, { question: 'É possível remover localização GPS?', answer: 'Sim. Coordenadas compatíveis aparecem no relatório e são removidas pelos modos adequados.' }, { question: 'Funciona com PDF?', answer: 'Sim. Detecta campos como autor, título, criador, produtor, assunto, palavras-chave e datas.' }, { question: 'O original é alterado?', answer: 'Não. Uma nova cópia é criada sem sobrescrever o original.' }], footer: 'Limpeza privada de arquivos no navegador.',
  },
  ko: {
    title: '사진·이미지·PDF 메타데이터 무료 제거', description: '사진, 이미지, PDF의 EXIF, GPS, 카메라, 작성자, 날짜 메타데이터를 업로드 없이 브라우저에서 무료로 제거하세요.',
    h1: '사진, 이미지 및 PDF용 무료 메타데이터 제거기', lead: '공유하기 전에 GPS, EXIF, 카메라, 작성자, 기기, 날짜 같은 숨은 정보를 확인하고 제거하세요. 모든 처리는 브라우저 안에서 이루어집니다.', privateLabel: '개인정보 보호 중심 설계', benefits: ['서버 업로드 없음', '계정 필요 없음', '정리 후 다시 확인'],
    uploadTitle: '파일을 놓아 개인정보 검사를 시작하세요', uploadText: '하나 이상의 파일을 선택하거나 클립보드의 이미지를 붙여넣을 수 있습니다.', choose: '파일 선택', localTitle: '파일은 내 기기에 그대로 있습니다.', localText: '분석, 정리, 검증은 이 브라우저에서 실행됩니다. 파일을 전송하거나 저장하지 않습니다.',
    howKicker: '지우기 전에 확인', howTitle: '파일이 드러내는 정보를 확인하고 필요한 항목만 제거하세요.', steps: [{ title: '탐지', text: '지원되는 EXIF, GPS, IPTC, XMP, 카메라 및 PDF 필드를 찾습니다.' }, { title: '설명', text: '기술 필드를 이해하기 쉬운 개인정보 정보로 바꿔 보여 줍니다.' }, { title: '선택', text: '개인정보, 전체, 사진가 또는 사용자 지정 정리를 선택합니다.' }, { title: '검증', text: '정리된 복사본을 다시 분석해 남은 정보를 보여 줍니다.' }],
    aboutKicker: '메타데이터와 개인정보', aboutTitle: '메타데이터 제거기는 무엇을 하나요?', about: ['메타데이터는 보이는 콘텐츠와 함께 저장되는 정보입니다. 사진에는 GPS 좌표, 촬영 날짜, 카메라와 렌즈, 일련번호, 작성자, 편집 기록이 포함될 수 있습니다. PDF에는 제목, 작성자, 생성 프로그램, 제작자, 키워드, 날짜가 남을 수 있습니다.', '이 도구는 파일을 바꾸기 전에 탐지된 필드를 보여 줍니다. 민감한 정보만 제거하거나 지원되는 메타데이터 전체를 지우거나, 가능한 형식에서는 안전한 촬영 설정을 유지할 수 있습니다.', '처리는 브라우저 안에서 이루어지며 원본을 덮어쓰지 않습니다. 정리된 복사본을 다시 검사하므로 공유 전에 결과를 확인할 수 있습니다.'],
    guideTitle: '사진 또는 PDF 메타데이터 제거 방법', guide: [{ title: '파일 추가', text: 'JPG, PNG, WebP 또는 PDF를 선택하고 로컬 분석을 기다립니다.' }, { title: '확인하고 선택', text: '위치, 신원, 기기, 날짜, 기술 정보를 확인한 뒤 정리 방식을 선택합니다.' }, { title: '검증된 복사본 저장', text: '결과를 다시 검사하며 원본은 그대로 유지됩니다.' }],
    faqTitle: '메타데이터 제거 자주 묻는 질문', faqIntro: 'EXIF, GPS, 이미지 및 PDF에 대한 간단한 답변입니다.', faqs: [{ question: '사진 메타데이터는 어떻게 지우나요?', answer: 'JPG, PNG 또는 WebP를 선택하고 필드를 확인한 뒤 정리 방식과 검증된 복사본을 선택합니다.' }, { question: '이미지가 업로드되나요?', answer: '아니요. 파일 읽기와 정리는 브라우저에서 로컬로 처리됩니다.' }, { question: 'GPS 위치를 제거할 수 있나요?', answer: '지원되는 GPS 좌표는 보고서에 표시되며 적절한 모드에서 제거됩니다.' }, { question: 'PDF도 지원하나요?', answer: '예. 작성자, 제목, 생성자, 제작자, 주제, 키워드, 날짜 등을 지원합니다.' }, { question: '원본이 바뀌나요?', answer: '아니요. 원본을 덮어쓰지 않고 새 복사본을 만듭니다.' }], footer: '브라우저에서 처리하는 비공개 파일 정리.',
  },
  it: {
    title: 'Rimuovi metadati da foto, immagini e PDF gratis', description: 'Elimina gratis metadati EXIF, GPS, fotocamera, autore e date da foto, immagini e PDF, senza caricare i file.',
    h1: 'Rimozione metadati gratuita per foto, immagini e PDF', lead: 'Controlla e rimuovi dati nascosti come GPS, EXIF, fotocamera, autore, dispositivo e date prima di condividere. Tutto avviene nel browser.', privateLabel: 'Privacy fin dalla progettazione', benefits: ['Nessun caricamento', 'Nessun account', 'Verifica dopo la pulizia'],
    uploadTitle: 'Trascina i file per avviare la scansione', uploadText: 'Scegli uno o più file oppure incolla un’immagine dagli appunti.', choose: 'Scegli file', localTitle: 'I file restano sul tuo dispositivo.', localText: 'Analisi, pulizia e verifica vengono eseguite in questo browser. I file non vengono inviati né archiviati.',
    howKicker: 'Controlla prima di rimuovere', howTitle: 'Scopri cosa rivela il file ed elimina solo ciò che serve.', steps: [{ title: 'Rileva', text: 'Trova i campi EXIF, GPS, IPTC, XMP, fotocamera e PDF supportati.' }, { title: 'Spiega', text: 'Traduce i campi tecnici in informazioni chiare sulla privacy.' }, { title: 'Scegli', text: 'Usa pulizia privacy, completa, fotografo o personalizzata.' }, { title: 'Verifica', text: 'Analizza di nuovo la copia e mostra le informazioni rimaste.' }],
    aboutKicker: 'Metadati e privacy', aboutTitle: 'Cosa fa uno strumento di rimozione metadati?', about: ['I metadati sono informazioni salvate insieme al contenuto visibile. Una foto può contenere coordinate GPS, data, fotocamera, obiettivo, numero di serie, autore o cronologia di modifica. Un PDF può rivelare titolo, autore, applicazione, produttore, parole chiave e date.', 'Lo strumento mostra i campi rilevati prima di modificare il file. Puoi rimuovere i dati sensibili, eliminare tutti i metadati supportati oppure conservare impostazioni fotografiche sicure quando il formato lo consente.', 'L’elaborazione avviene nel browser, senza sovrascrivere l’originale e senza inviare il file a un server. La copia pulita viene analizzata di nuovo per verificare il risultato prima della condivisione.'],
    guideTitle: 'Come rimuovere metadati da una foto o un PDF', guide: [{ title: 'Aggiungi il file', text: 'Seleziona JPG, PNG, WebP o PDF e attendi l’analisi locale.' }, { title: 'Controlla e scegli', text: 'Esamina posizione, identità, dispositivo, date e dati tecnici, quindi scegli la pulizia.' }, { title: 'Scarica la copia verificata', text: 'Il risultato viene scansionato di nuovo e l’originale resta intatto.' }],
    faqTitle: 'Domande sulla rimozione dei metadati', faqIntro: 'Risposte chiare su EXIF, GPS, immagini e PDF.', faqs: [{ question: 'Come eliminare i metadati da una foto?', answer: 'Scegli JPG, PNG o WebP, controlla i campi, seleziona la pulizia e scarica la copia verificata.' }, { question: 'Le immagini vengono caricate?', answer: 'No. I file vengono letti e puliti localmente nel browser.' }, { question: 'Si può rimuovere la posizione GPS?', answer: 'Sì. Le coordinate supportate compaiono nel rapporto e vengono eliminate dalle modalità adatte.' }, { question: 'Funziona con i PDF?', answer: 'Sì, per autore, titolo, creatore, produttore, oggetto, parole chiave e date.' }, { question: 'L’originale viene modificato?', answer: 'No. Viene creata una nuova copia.' }], footer: 'Pulizia privata dei file nel browser.',
  },
  id: {
    title: 'Hapus metadata foto, gambar, dan PDF gratis', description: 'Hapus metadata EXIF, GPS, kamera, penulis, dan tanggal dari foto, gambar, dan PDF gratis tanpa mengunggah file.',
    h1: 'Penghapus metadata gratis untuk foto, gambar, dan PDF', lead: 'Periksa dan hapus data tersembunyi seperti GPS, EXIF, kamera, penulis, perangkat, dan tanggal sebelum berbagi. Semua diproses lokal di browser.', privateLabel: 'Privasi sejak awal', benefits: ['Tanpa unggah ke server', 'Tanpa akun', 'Verifikasi setelah dibersihkan'],
    uploadTitle: 'Letakkan file untuk memulai pemindaian', uploadText: 'Pilih satu atau beberapa file. Anda juga dapat menempelkan gambar dari papan klip.', choose: 'Pilih file', localTitle: 'File tetap berada di perangkat Anda.', localText: 'Analisis, pembersihan, dan verifikasi berjalan di browser ini. File tidak dikirim atau disimpan.',
    howKicker: 'Periksa sebelum menghapus', howTitle: 'Ketahui apa yang diungkap file dan hapus hanya data yang diperlukan.', steps: [{ title: 'Deteksi', text: 'Menemukan bidang EXIF, GPS, IPTC, XMP, kamera, dan PDF yang didukung.' }, { title: 'Jelaskan', text: 'Mengubah bidang teknis menjadi informasi privasi yang mudah dipahami.' }, { title: 'Pilih', text: 'Gunakan pembersihan privasi, penuh, fotografer, atau khusus.' }, { title: 'Verifikasi', text: 'Memindai ulang salinan bersih dan menampilkan data yang tersisa.' }],
    aboutKicker: 'Metadata dan privasi', aboutTitle: 'Apa fungsi penghapus metadata?', about: ['Metadata adalah informasi yang disimpan bersama konten yang terlihat. Foto dapat memuat koordinat GPS, tanggal, kamera, lensa, nomor seri, nama pembuat, atau riwayat penyuntingan. PDF dapat mengungkap judul, penulis, aplikasi pembuat, produsen, kata kunci, dan tanggal.', 'Alat ini menampilkan bidang yang ditemukan sebelum mengubah file. Anda dapat menghapus data sensitif, membersihkan semua metadata yang didukung, atau mempertahankan pengaturan fotografi yang aman bila formatnya memungkinkan.', 'Pemrosesan berlangsung di browser tanpa menimpa file asli atau mengirim file ke server. Salinan bersih dipindai lagi agar Anda dapat memastikan hasilnya sebelum berbagi.'],
    guideTitle: 'Cara menghapus metadata foto atau PDF', guide: [{ title: 'Tambahkan file', text: 'Pilih JPG, PNG, WebP, atau PDF lalu tunggu analisis lokal.' }, { title: 'Periksa dan pilih', text: 'Tinjau lokasi, identitas, perangkat, tanggal, dan data teknis lalu pilih pembersihan.' }, { title: 'Unduh salinan terverifikasi', text: 'Hasil dipindai ulang dan file asli tetap utuh.' }],
    faqTitle: 'Pertanyaan tentang penghapusan metadata', faqIntro: 'Jawaban singkat tentang EXIF, GPS, gambar, dan PDF.', faqs: [{ question: 'Bagaimana cara menghapus metadata foto?', answer: 'Pilih JPG, PNG, atau WebP, periksa bidang, pilih pembersihan, lalu unduh salinan terverifikasi.' }, { question: 'Apakah gambar saya diunggah?', answer: 'Tidak. File dibaca dan dibersihkan secara lokal di browser.' }, { question: 'Bisakah lokasi GPS dihapus?', answer: 'Ya. Koordinat yang didukung ditampilkan di laporan dan dihapus oleh mode yang sesuai.' }, { question: 'Apakah mendukung PDF?', answer: 'Ya. Bidang umum seperti penulis, judul, pembuat, produsen, subjek, kata kunci, dan tanggal didukung.' }, { question: 'Apakah file asli berubah?', answer: 'Tidak. Alat membuat salinan baru dan tidak menimpa file asli.' }], footer: 'Pembersihan file privat di browser Anda.',
  },
};
